// Content script that detects AI-generated images on web pages
// and allows users to import them for certification

interface DetectedImage {
  url: string;
  element: HTMLImageElement;
  source: string;
  prompt?: string;
}

class ProofOfArtExtension {
  private detectedImages: DetectedImage[] = [];
  private observer: MutationObserver | null = null;

  constructor() {
    this.init();
  }

  private init() {
    // Listen for messages from popup
    chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
      if (request.action === 'getDetectedImages') {
        sendResponse({ images: this.detectedImages });
      } else if (request.action === 'captureImage') {
        this.captureImage(request.imageUrl).then(sendResponse);
        return true; // Keep channel open for async response
      }
    });

    // Scan for images on page load
    this.scanForImages();

    // Set up mutation observer to detect dynamically added images
    this.setupObserver();

    // Add context menu option for images
    this.addContextMenuListener();
  }

  private scanForImages() {
    const images = document.querySelectorAll('img');
    
    images.forEach((img) => {
      if (this.isLikelyAIGenerated(img)) {
        this.detectedImages.push({
          url: img.src,
          element: img,
          source: this.detectSource(),
          prompt: this.extractPromptFromPage(),
        });
      }
    });

    console.log(`Proof-of-Art: Detected ${this.detectedImages.length} potential AI images`);
  }

  private isLikelyAIGenerated(img: HTMLImageElement): boolean {
    // Heuristics to detect AI-generated images
    const aiPlatforms = [
      'openai.com',
      'midjourney.com',
      'stability.ai',
      'dall-e',
      'stablediffusion',
      'leonardo.ai',
      'replicate.com',
    ];

    const src = img.src.toLowerCase();
    const alt = img.alt?.toLowerCase() || '';
    const parentText = img.parentElement?.textContent?.toLowerCase() || '';

    // Check if from known AI platforms
    if (aiPlatforms.some(platform => src.includes(platform))) {
      return true;
    }

    // Check for AI-related keywords
    const aiKeywords = ['ai generated', 'ai art', 'generated by', 'midjourney', 'dall-e', 'stable diffusion'];
    if (aiKeywords.some(keyword => alt.includes(keyword) || parentText.includes(keyword))) {
      return true;
    }

    // Check image dimensions (AI images often have specific resolutions)
    const commonAIResolutions = [
      { width: 1024, height: 1024 },
      { width: 512, height: 512 },
      { width: 768, height: 768 },
      { width: 1024, height: 768 },
    ];

    if (commonAIResolutions.some(res => 
      Math.abs(img.naturalWidth - res.width) < 10 && 
      Math.abs(img.naturalHeight - res.height) < 10
    )) {
      return true;
    }

    return false;
  }

  private detectSource(): string {
    const hostname = window.location.hostname;
    
    const platformMap: Record<string, string> = {
      'midjourney.com': 'Midjourney',
      'openai.com': 'DALL-E',
      'stability.ai': 'Stable Diffusion',
      'leonardo.ai': 'Leonardo AI',
      'replicate.com': 'Replicate',
      'nightcafe.studio': 'NightCafe',
    };

    for (const [domain, platform] of Object.entries(platformMap)) {
      if (hostname.includes(domain)) {
        return platform;
      }
    }

    return 'Unknown';
  }

  private extractPromptFromPage(): string | undefined {
    // Try to find prompt text near images
    const promptSelectors = [
      '[data-prompt]',
      '.prompt',
      '[class*="prompt"]',
      '[id*="prompt"]',
      'textarea[placeholder*="prompt"]',
      'input[placeholder*="prompt"]',
    ];

    for (const selector of promptSelectors) {
      const element = document.querySelector(selector);
      if (element) {
        const prompt = element.getAttribute('data-prompt') || 
                      (element as HTMLInputElement).value || 
                      element.textContent;
        if (prompt && prompt.length > 10) {
          return prompt.trim();
        }
      }
    }

    return undefined;
  }

  private setupObserver() {
    this.observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        mutation.addedNodes.forEach((node) => {
          if (node.nodeName === 'IMG') {
            const img = node as HTMLImageElement;
            if (this.isLikelyAIGenerated(img)) {
              this.detectedImages.push({
                url: img.src,
                element: img,
                source: this.detectSource(),
                prompt: this.extractPromptFromPage(),
              });
            }
          }
        });
      });
    });

    this.observer.observe(document.body, {
      childList: true,
      subtree: true,
    });
  }

  private addContextMenuListener() {
    document.addEventListener('contextmenu', (e) => {
      const target = e.target as HTMLElement;
      if (target.tagName === 'IMG') {
        const img = target as HTMLImageElement;
        // Store the image for context menu action
        (window as any).__proofOfArtSelectedImage = {
          url: img.src,
          prompt: this.extractPromptFromPage(),
          source: this.detectSource(),
        };
      }
    });
  }

  private async captureImage(imageUrl: string): Promise<{ success: boolean; data?: Blob }> {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      return { success: true, data: blob };
    } catch (error) {
      console.error('Failed to capture image:', error);
      return { success: false };
    }
  }
}

// Initialize extension
new ProofOfArtExtension();

// Add visual indicator for detected AI images
const style = document.createElement('style');
style.textContent = `
  .proof-of-art-detected {
    position: relative;
    box-shadow: 0 0 0 2px #00ffff !important;
  }
  .proof-of-art-detected::after {
    content: "🎨 AI Detected";
    position: absolute;
    top: 8px;
    right: 8px;
    background: rgba(0, 255, 255, 0.9);
    color: black;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 12px;
    font-weight: bold;
    pointer-events: none;
  }
`;
document.head.appendChild(style);

// Mark detected images
setTimeout(() => {
  document.querySelectorAll('img').forEach((img) => {
    if (new ProofOfArtExtension()['isLikelyAIGenerated'](img)) {
      img.classList.add('proof-of-art-detected');
    }
  });
}, 1000);